#!/bin/bash

####################################################################
# author : Mahmoud Mohamed (Ozil)  <https://github.com/mmsaeed509> #
####################################################################

RUNNING_SONG=$(mpc current)
COVER="$HOME/.ncmpcpp/cover/album_cover.jpg"
COVER_SIZE="400"
MUSIC_DIR="$HOME/Music"

#path to current song
file="$MUSIC_DIR/$(mpc --format %file% current)"
album="${file%/*}"
#search for cover image
art=$(find "$album"  -maxdepth 1 | grep -m 1 ".*\.\(jpg\|png\|gif\|bmp\)")
if [ "$art" = "" ]; then
  art="$HOME/.ncmpcpp/cover/album_cover.jpg"
fi

# send a notification with a cover photo for the running song  
dunstify -u low --replace=69 -i ${art} "Playing : $RUNNING_SONG"

#copy and resize image to destination
ffmpeg -loglevel 0 -y -i "$art" -vf "scale=$COVER_SIZE:-1" "$COVER"

