#!/usr/bin/env bash

#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS         #
#                                   #
#####################################

# Environtment path #
export PATH="${PATH}:$HOME/.config/bspwm/bin:$HOME/.config/bspwm/rofi/bin:$HOME/.local/bin"

# bspwm config directory #
BSPWM_DIR="$HOME/.config/bspwm"

# colors directory #
XRES="$HOME/.Xresources.d"

##  ------------------------- Configurations -------------------------  ##

# set keyboard Layouts #
setxkbmap -layout $(grep -oP 'keyboard-layouts = \K.*' "${BSPWM_DIR}/exodia.conf")
setxkbmap -option 'grp:alt_shift_toggle'

# Updating Color Schemes #
cat ${BSPWM_DIR}/colorSchemes/$(grep -oP 'color-scheme = \K.*' "${BSPWM_DIR}/exodia.conf")> "${XRES}"/colors

# Solve java apps issues (e.g. JetBrains IDEs like PyCharm, CLion, etc). #
export _JAVA_AWT_WM_NONREPARENTING=1 

# setup connected monitors #

# No. monitors #
NUM_OF_MONITORS=$(xrandr --listmonitors | grep -c "^ ")

if [[ ${NUM_OF_MONITORS} -ge 1 ]]; 
	then
    	bspmonitors
fi

# Workspaces Configurations #
workspaces() {
	
	name=1
	
	for monitor in `bspc query -M`; 
		do

			bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
			let name++

	done

}

workspaces

# load bspwm Configurations #
bspconfig

# Manage all the unmanaged windows remaining from a previous session. #
bspc wm --adopt-orphans

# Window rules #
bsprules

##  ------------------------- Autostart Apps -------------------------  ##

# Kill if already running #
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc picom

# Lauch xsettingsd daemon #
xsettingsd --config="${BSPWM_DIR}"/xsettingsd &

# polkit agent #
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon #
sxhkd -c "${BSPWM_DIR}"/keybinding/$(grep -oP 'keybinding = \K.*' "${BSPWM_DIR}/exodia.conf") &

# Enable Super Keys For Menu #
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power manager #
xfce4-power-manager &

# Fix cursor #
xsetroot -cursor_name left_ptr

# restore wallpaper #
feh --no-fehbg --bg-fill /usr/share/backgrounds/$(grep -oP 'background = \K.*' "${BSPWM_DIR}/exodia.conf")

# enable num lock #
numlockx &

# Start mpd #
exec mpd &

# start bspwm scripts #
bspcolors
bspcomp
bspbar
bspdunst 
bspfloat &

# Lauch Exodia OS Assistant #

STATUS=$(grep -Po 'exoida-assistant-auto-start\s*=\s*\K.*' ${BSPWM_DIR}/exodia.conf)

if [[ ${STATUS} == "true" ]]; 
	then
    	exodia-assistant
fi
