#!/usr/bin/env bash

#
# Copyright (C) 29-April 2022 Mahmoud Mohamed (Ozil)  <https://github.com/mmsaeed509>
# Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
#

## paths
CFG="$HOME/.config"
BSP="$HOME/.config/bspwm"
XRES="$HOME/.Xresources.d"

## Set Style
set_style () {
	# apply wallpaper
	feh --bg-fill /usr/share/backgrounds/${1}
	
	# apply color-scheme
	cat "$BSP"/themes/${2} > "$XRES"/colors
	
	# set gtk theme, icons and cursor
	if [[ `pidof xsettingsd` ]]; then
		sed -i -e "s|Net/ThemeName .*|Net/ThemeName \"$3\"|g" ${HOME}/.xsettingsd
		sed -i -e "s|Net/IconThemeName .*|Net/IconThemeName \"$4\"|g" ${HOME}/.xsettingsd
		sed -i -e "s|Gtk/CursorThemeName .*|Gtk/CursorThemeName \"$5\"|g" ${HOME}/.xsettingsd
	else
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=\"$3\"/g" ${HOME}/.gtkrc-2.0
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=\"$4\"/g" ${HOME}/.gtkrc-2.0
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=\"$5\"/g" ${HOME}/.gtkrc-2.0
		
		sed -i -e "s/gtk-theme-name=.*/gtk-theme-name=$3/g" ${CFG}/gtk-3.0/settings.ini
		sed -i -e "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$4/g" ${CFG}/gtk-3.0/settings.ini
		sed -i -e "s/gtk-cursor-theme-name=.*/gtk-cursor-theme-name=$5/g" ${CFG}/gtk-3.0/settings.ini
	fi
	zz

	# ---------------------------- launch a custom Polybar if it exists ----------------------------

	if [[ "$6" == "" ]]
	then
		echo "defaultBar">~/.config/bspwm/selectedThemeName

	else 
		echo "$6">~/.config/bspwm/selectedThemeName
	fi

	# ---------------------------- launch a custom Polybar if it exists ----------------------------

	# ----- reload config ----- #
	pkill polybar
	bspc wm -r
}

set_style "${1}" "${2}" "${3}" "${4}" "${5}" "${6}"
