#!/bin/bash

## Open links in firefox
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
cmd="google-chrome-stable --new-tab"

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit facebook youtube weather apps cava mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--mail" ]]; then
	close_dash && ${cmd} "https://mail.google.com"

elif [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com/mmsaeed509"

elif [[ "$1" == "--rd" ]]; then
	close_dash && ${cmd} "https://reddit.com"

elif [[ "$1" == "--fb" ]]; then
	close_dash && ${cmd} "https://facebook.com"

elif [[ "$1" == "--yt" ]]; then
	close_dash && ${cmd} "https://youtube.com"

fi
