#!/bin/bash


# ---------------------------- No. 0 -- > Menu Theme ----------------------------

if [[ "$1" == "" ]]
then
	            
	
  echo -e "\e[1;37m -Beach  	 Apply Beach Theme \e[0m"
  echo -e "\e[1;31m -Blade          Apply Blade Theme \e[0m"
  echo -e "\e[1;33m -Bouquet        Apply Bouquet Theme \e[0m"
  echo -e "\e[0;35m -Cyberpunk      Apply Cyberpunk Theme \e[0m"
  echo -e "\e[0;35m -Dracula        Apply Dracula Theme \e[0m"
  echo -e "\e[1;31m -Flowers        Apply Flowers Theme \e[0m"
  echo -e "\e[0;32m -Forest         Apply Forest Theme \e[0m"
  echo -e "\e[0;33m -Groot          Apply Groot Theme \e[0m"
  echo -e "\e[1;33m -Gruvbox        Apply Gruvbox Theme \e[0m"
  echo -e "\e[0;36m -Hack           Apply Hack Theme \e[0m"
  echo -e "\e[0;35m -Keyboards      Apply Keyboards Theme \e[0m"
  echo -e "\e[1;37m -Light          Apply Light Theme \e[0m"
  echo -e "\e[1;37m -Manhattan      Apply Manhattan Theme \e[0m"
  echo -e "\e[1;37m -Nord           Apply Nord Theme \e[0m"
  echo -e "\e[1;37m -Nordic         Apply Nordic Theme \e[0m"
  echo -e "\e[0;36m -Rick           Apply Rick Theme \e[0m"
  echo -e "\e[0;35m -Spark          Apply Spark Theme \e[0m"
  echo -e "\e[0;36m -Tealize        Apply Tealize Theme \e[0m"
  echo -e "\e[1;31m -Wave           Apply Wave Theme \e[0m"
  echo -e "\e[1;32m -HackTheBox     Apply HackTheBox Theme \e[0m"
	
	
fi


# ---------------------------- No. 1 -- > Beach Theme ----------------------------

if [[ "$1" == "-Beach" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 2 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 255 -cB 255 -cG 255 -b 100
	
fi

# ---------------------------- No. 2 -- > Blade Theme ----------------------------

if [[ "$1" == "-Blade" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 255 -cB 0 -cG 0 -b 100
	facer_rgb.py -m 0 -z 2 -cR 255 -cB 0 -cG 0 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 0 -cG 0 -b 100
	facer_rgb.py -m 0 -z 4 -cR 255 -cB 0 -cG 0 -b 100
	
fi

# ---------------------------- No. 3 -- > Bouquet Theme ----------------------------

if [[ "$1" == "-Bouquet" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 255 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 2 -cR 255 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 255 -cB 0 -cG 255 -b 100
	
fi

# ---------------------------- No. 4 -- > Cyberpunk Theme ----------------------------

if [[ "$1" == "-Cyberpunk" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 2 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 3 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 4 -cR 175 -cB 255 -cG 0 -b 100
	
fi

# ---------------------------- No. 5 -- > Dracula Theme ----------------------------

if [[ "$1" == "-Dracula" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 2 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 3 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 4 -cR 175 -cB 255 -cG 0 -b 100
	
fi

# ---------------------------- No. 6 -- > Flowers Theme ----------------------------

if [[ "$1" == "-Flowers" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 2 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 255 -cB 255 -cG 255 -b 100
	
fi

# ---------------------------- No. 7 -- > Forest Theme ----------------------------

if [[ "$1" == "-Forest" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 0 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 2 -cR 0 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 3 -cR 0 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 0 -cB 0 -cG 255 -b 100
	
fi

# ---------------------------- No. 8 -- > Groot Theme ----------------------------

if [[ "$1" == "-Groot" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 152 -cB 74 -cG 118 -b 100
	facer_rgb.py -m 0 -z 2 -cR 152 -cB 74 -cG 118 -b 100
	facer_rgb.py -m 0 -z 3 -cR 152 -cB 74 -cG 118 -b 100
	facer_rgb.py -m 0 -z 4 -cR 152 -cB 74 -cG 118 -b 100
	
fi

# ---------------------------- No. 9 -- > Gruvbox Theme ----------------------------

if [[ "$1" == "-Gruvbox" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 255 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 2 -cR 255 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 255 -cB 0 -cG 255 -b 100
	
fi

# ---------------------------- No. 10 -- > Hack Theme ----------------------------

if [[ "$1" == "-Hack" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 4 -cB 181 -cG 172 -b 100
	facer_rgb.py -m 0 -z 2 -cR 4 -cB 181 -cG 172 -b 100
	facer_rgb.py -m 0 -z 3 -cR 4 -cB 181 -cG 172 -b 100
	facer_rgb.py -m 0 -z 4 -cR 4 -cB 181 -cG 172 -b 100
	
fi

# ---------------------------- No. 11 -- > Keyboards Theme ----------------------------

if [[ "$1" == "-Keyboards" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 2 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 3 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 4 -cR 175 -cB 255 -cG 0 -b 100
	
fi

# ---------------------------- No. 12 -- > Light Theme ----------------------------

if [[ "$1" == "-Light" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 2 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 255 -cB 255 -cG 255 -b 100
	
fi

# ---------------------------- No. 13 -- > Manhattan Theme ----------------------------

if [[ "$1" == "-Manhattan" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 255 -cB 186 -cG 134 -b 100
	facer_rgb.py -m 0 -z 2 -cR 255 -cB 186 -cG 134 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 186 -cG 134 -b 100
	facer_rgb.py -m 0 -z 4 -cR 255 -cB 186 -cG 134 -b 100
	
fi

# ---------------------------- No. 14 -- > Nord Theme ----------------------------

if [[ "$1" == "-Nord" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 2 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 255 -cB 255 -cG 255 -b 100
	
fi

# ---------------------------- No. 15 -- > Nordic Theme ----------------------------

if [[ "$1" == "-Nordic" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 2 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 255 -cB 255 -cG 255 -b 100
	
fi

# ---------------------------- No. 16 -- > Pastel Theme ----------------------------

if [[ "$1" == "-Pastel" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 246 -cB 227 -cG 207 -b 100
	facer_rgb.py -m 0 -z 2 -cR 0 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 3 -cR 255 -cB 255 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 4 -cB 181 -cG 172 -b 100
	
fi

# ---------------------------- No. 17 -- > Rick Theme ----------------------------

if [[ "$1" == "-Rick" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 152 -cB 74 -cG 118 -b 100
	facer_rgb.py -m 0 -z 2 -cR 152 -cB 74 -cG 118 -b 100
	facer_rgb.py -m 0 -z 3 -cR 152 -cB 74 -cG 118 -b 100
	facer_rgb.py -m 0 -z 4 -cR 152 -cB 74 -cG 118 -b 100
	
fi

# ---------------------------- No. 18 -- > Spark Theme ----------------------------

if [[ "$1" == "-Spark" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 2 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 3 -cR 175 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 4 -cR 175 -cB 255 -cG 0 -b 100
	
fi

# ---------------------------- No. 19 -- > Tealize Theme ----------------------------

if [[ "$1" == "-Tealize" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 41 -cB 164 -cG 172 -b 100
	facer_rgb.py -m 0 -z 2 -cR 103 -cB 183 -cG 194 -b 100
	facer_rgb.py -m 0 -z 3 -cR 103 -cB 183 -cG 194 -b 100
	facer_rgb.py -m 0 -z 4 -cR 32 -cB 141 -cG 149 -b 100
	
fi

# ---------------------------- No. 20 -- > Wave Theme ----------------------------

if [[ "$1" == "-Wave" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 152 -cB 74 -cG 118 -b 100
	facer_rgb.py -m 0 -z 2 -cR 152 -cB 74 -cG 118 -b 100
	facer_rgb.py -m 0 -z 3 -cR 152 -cB 74 -cG 118 -b 100
	facer_rgb.py -m 0 -z 4 -cR 152 -cB 74 -cG 118 -b 100
	
fi

# ---------------------------- No. 21 -- > Hack The Box Theme ----------------------------

if [[ "$1" == "-HackTheBox" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 0 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 2 -cR 0 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 3 -cR 0 -cB 0 -cG 255 -b 100
	facer_rgb.py -m 0 -z 4 -cR 0 -cB 0 -cG 255 -b 100
	
fi

# ---------------------------- No. 22 -- > BlackArch Theme ----------------------------

if [[ "$1" == "-BlackArch" ]]
then
	
	facer_rgb.py -m 0 -z 1 -cR 0 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 2 -cR 0 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 3 -cR 0 -cB 255 -cG 0 -b 100
	facer_rgb.py -m 0 -z 4 -cR 0 -cB 255 -cG 0 -b 100
	
fi

