#!/bin/bash

#
# @author : Mahmoud Mohamed (Ozil)  <https://github.com/mmsaeed509>
# Copyright (C) GNU-GPL3
#

ssid=$(iwgetid -r)

if [[ "$ssid" == "" ]]; then
  echo "睊 disconnected"

else
  echo "直 $ssid"
fi
