#!/bin/bash

#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS         #
#                                   #
#####################################

ssid=$(iwgetid -r)

if [[ "$ssid" == "" ]]; then
  echo "睊 disconnected"

else
  echo "直 $ssid"
fi

ssid=$(iwgetid -r)
printf "󰤨  $ssid " ;;

