#!/bin/bash

#
# Copyright (C) 2022 Mahmoud Mohamed (Ozil)  <https://github.com/mmsaeed509>
# LICENSE © GNU-GPL3
#

ssid=$(iwgetid -r)

if [[ "$ssid" == "" ]]; then
  echo "睊 disconnected"

else
  echo "直 $ssid"
fi
